# Generated by Django 6.1.1 on 2026-09-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('GAME', 'Gaming & Esports'), ('TECH', 'Technology'), ('FUN', 'Movies & TV'), ('GENERAL', 'General stuff'), ('SPORTS', 'Sports')], default='GENERAL', max_length=200),
        ),
    ]
